[package]
name = "galette"
version = "0.2.0"
authors = ["Simon Frankau <sgf@arbitrary.name>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
itertools = "0.9.0"
thiserror = "1.0.23"

[lib]
name = "galette"

[[bin]]
name = "galette"
